name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    include:
      - refs/tags/r*

variables:
  - group: ApiKeys-mm-cloud
  - group: GitSSHGroup
  - group: OctoDefault
  - name: solutionFile
    value: 'FireGuardians.sln'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

stages:
  - stage: Build
    jobs:
      - job: linux
        displayName: Docker build
        pool:
          name: meshmakers-ci-agents
        steps:
          - template: update-build-number.yml
          - checkout: self
            clean: true
            submodules: recursive
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: '$(SSHKnownHosts)'
              sshPublicKey: '$(SSHPublicKey)'
              sshPassphrase: '$(SSHPassphrase)'
              sshKeySecureFile: '$(SSHPrivateKeyFile)'            
          - template: set-version.yml
          - template: download-ca.yml
          - task: DotNetCoreCLI@2
            displayName: 'Running tests'
            inputs:
              command: 'test'
              projects: |
                '**/*Tests.csproj'
                !'**/*SystemTests.csproj'
              testRunTitle: 'CI'
          - template: build-and-push-docker-image.yml
            parameters:
              ContainerRegistry: $(DockerRegistryPublicConnection)
              Repository: meshmakers/fire-guardians-app
              Dockerfile: src/FireGuardiansWebApp/Dockerfile
              PrivateRegistry: $(DockerRegistryPrivateUri)
          - template: handle-artifacts.yml